spring:
  application:
    name: microservice-sidecar
server:
  port: 8070  #指定服务端口
eureka:
  datacenter: SpringCloud   # 修改 http://localhost:8761 地址 Eureka 首页上面 System Status 的 Data center 显示信息
  environment: Test         # 修改 http://localhost:8761 地址 Eureka 首页上面 System Status 的 Environment 显示信息
  client:
    service-url:
      defaultZone: http://kevin:123456@localhost:8761/eureka
  #注册IP
  instance:
    prefer-ip-address: true
#打印日志
logging:
  level:
    com.netflix: debug
#异构微服务的配置， port 代表异构微服务的端口；health-uri 代表异构微服务的操作链接地址
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json