server:
  port: 8103
spring:
  application:
    name: microservice-consumer-movie-feign-with-hystrix-factory
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://kevin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
