server:
  port: 8011
spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://kevin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user:
  ribbon: #配置负载均衡的规则-轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #配置负载均衡的规则：随机
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule