server:
  port: 8100
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://kevin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true